name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Verify source
      run: make verify

    - name: Install
      run: make install PREFIX="$RUNNER_TEMP/sql-doctor"

    - name: Verify install
      run: make verify-install PREFIX="$RUNNER_TEMP/sql-doctor"
