on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      # - name: Debug Secrets (Use with Caution!)
      #   run: |
          # echo "OPENAI_KEY:"
          # echo ${{ secrets.OPENAI_KEY }} | sed 's/./& /g'
          # echo "OPENAI_API_BASE:"
          # echo ${{ secrets.OPENAI_API_BASE }} | sed 's/./& /g'
          # echo "GITHUB_TOKEN:"
          # echo ${{ secrets.TOKEN }} | sed 's/./& /g'
      - name: PR Agent action step
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
